package id.imperial.resourcepack.paper;
import id.imperial.resourcepack.common.*;import net.kyori.adventure.text.minimessage.MiniMessage;import org.bukkit.entity.Player;import org.bukkit.event.*;import org.bukkit.event.player.PlayerJoinEvent;import org.bukkit.plugin.java.JavaPlugin;import java.io.*;import java.nio.file.*;import java.util.concurrent.*;import java.util.*;
public final class ImperialResourcePackPaper extends JavaPlugin implements Listener{
 private final ExecutorService worker=Executors.newSingleThreadExecutor();private ResourcePackManager manager;private ResourcePackHost host;private volatile ResourcePackConfig config;
 @Override public void onEnable(){manager=new ResourcePackManager(getLogger());host=new ResourcePackHost(manager,getLogger());reload();getServer().getPluginManager().registerEvents(this,this);var cmd=Objects.requireNonNull(getCommand("irp"));var executor=new PaperCommand(this);cmd.setExecutor(executor);cmd.setTabCompleter(executor);}
 @Override public void onDisable(){host.close();worker.shutdown();}
 @EventHandler public void join(PlayerJoinEvent e){ResourcePackConfig c=config;if(c!=null&&c.enabled()&&c.deliveryEnabled())getServer().getScheduler().runTaskLater(this,()->send(e.getPlayer()),Math.max(1,c.sendDelayMs()/50));}
 void send(Player player){ResourcePackConfig c=config;ActivePack fallback=manager.active();if(c==null||fallback==null||c.publicUrl().isBlank())return;int protocol=player.getProtocolVersion();ActivePack selected=fallback;String detected="unknown("+protocol+")";if(c.versionMapping()){for(String version:MinecraftProtocolVersions.versionsFor(protocol)){Path f=manager.versionPack(packsDirectory(),version);if(f==null)continue;var r=manager.prepare(f,packsDirectory(),c);if(r.success()){selected=r.pack();detected=version+" (protocol "+protocol+")";break;}getLogger().warning("[ImperialResourcePack] Ignoring invalid version-mapped pack "+f.getFileName()+": "+r.message());}}getLogger().info("[ImperialResourcePack] Client protocol="+protocol+", detected-version="+detected+", sending="+selected.file().getFileName());player.setResourcePack(selected.id(),c.publicUrl(),selected.sha1(),MiniMessage.miniMessage().deserialize(c.prompt()),c.required());}
 synchronized String reload(){try{Path d=getDataFolder().toPath();Files.createDirectories(d);Path f=d.resolve("config.yml");if(Files.notExists(f))try(InputStream in=getResource("config.yml")){Files.copy(in,f);}config=ResourcePackConfig.load(f);Path packs=d.resolve(config.packsDirectory()).normalize();if(!packs.startsWith(d))return "Invalid packs-directory.";manager.scan(packs,config);host.start(config,worker);return "Reload complete.";}catch(Exception e){getLogger().severe(e.getMessage());return "Reload failed: "+e.getMessage();}}
 ResourcePackManager manager(){return manager;}ResourcePackHost host(){return host;}ResourcePackConfig config(){return config;}Path packsDirectory(){return getDataFolder().toPath().resolve(config.packsDirectory()).normalize();}
}