package id.imperial.resourcepack.paper;
import id.imperial.resourcepack.common.*;import org.bukkit.command.*;import org.jetbrains.annotations.NotNull;import java.nio.file.Path;import java.util.List;
final class PaperCommand implements TabExecutor{
 private static final String P="imperialresourcepack.admin";private final ImperialResourcePackPaper p;PaperCommand(ImperialResourcePackPaper p){this.p=p;}
 public boolean onCommand(@NotNull CommandSender s,@NotNull Command c,@NotNull String l,String[] a){if(!s.hasPermission(P)){s.sendMessage("[IRP] No permission.");return true;}if(a.length==0){s.sendMessage("[IRP] Usage: /irp <list|use <file>|info|reload|validate>");return true;}switch(a[0].toLowerCase(java.util.Locale.ROOT)){
 case "list"->{List<Path>x=p.manager().listValid(p.packsDirectory(),p.config());if(x.isEmpty())s.sendMessage("[IRP] No valid resource packs found.");else{Path z=p.manager().active()==null?null:p.manager().active().file();s.sendMessage("[IRP] Valid packs:");for(Path f:x)s.sendMessage(" - "+f.getFileName()+(f.equals(z)?" [ACTIVE]":""));}}
 case "use"->{if(a.length<2){s.sendMessage("[IRP] Usage: /irp use <file.zip>");return true;}var r=p.manager().activate(p.packsDirectory().resolve(a[1]),p.packsDirectory(),p.config());s.sendMessage(r.success()?"[IRP] Active pack changed to "+r.pack().file().getFileName()+".":"[IRP] Pack was NOT changed: "+r.message());}
 case "info"->{ActivePack x=p.manager().active();s.sendMessage("[IRP] "+(x==null?"No active pack.":x.file().getFileName()+" | size="+x.size()+" | SHA-1="+x.sha1Hex()+" | UUID="+x.id()+" | HTTP="+p.host().running()));}
 case "reload"->s.sendMessage("[IRP] "+p.reload());case "validate"->s.sendMessage("[IRP] "+p.manager().validateActive(p.config()).message());default->s.sendMessage("[IRP] Unknown subcommand. Usage: /irp <list|use <file>|info|reload|validate>");}return true;}
 public @NotNull List<String> onTabComplete(@NotNull CommandSender s,@NotNull Command c,@NotNull String l,String[] a){if(!s.hasPermission(P))return List.of();if(a.length==1)return part(List.of("list","use","info","reload","validate"),a[0]);if(a.length==2&&a[0].equalsIgnoreCase("use"))return part(p.manager().listValid(p.packsDirectory(),p.config()).stream().map(x->x.getFileName().toString()).toList(),a[1]);return List.of();}
 private static List<String> part(List<String>x,String in){String q=in.toLowerCase(java.util.Locale.ROOT);return x.stream().filter(v->v.toLowerCase(java.util.Locale.ROOT).startsWith(q)).sorted().toList();}
}