package id.imperial.resourcepack.velocity;
import com.velocitypowered.api.command.SimpleCommand;import id.imperial.resourcepack.common.*;import net.kyori.adventure.text.Component;import java.nio.file.Path;import java.util.List;
final class VelocityCommand implements SimpleCommand{
 private static final String P="imperialresourcepack.admin";private final ImperialResourcePackVelocity p;VelocityCommand(ImperialResourcePackVelocity p){this.p=p;}
 public void execute(Invocation i){if(!i.source().hasPermission(P)){say(i,"No permission.");return;}String[]a=i.arguments();if(a.length==0){say(i,"Usage: /irp <list|use <file>|info|reload|validate>");return;}switch(a[0].toLowerCase(java.util.Locale.ROOT)){
 case "list"->{List<Path>x=p.manager().listValid(p.packsDirectory(),p.config());if(x.isEmpty())say(i,"No valid resource packs found.");else{say(i,"Valid packs:");Path z=p.manager().active()==null?null:p.manager().active().file();for(Path f:x)say(i," - "+f.getFileName()+(f.equals(z)?" [ACTIVE]":""));}}
 case "use"->{if(a.length<2){say(i,"Usage: /irp use <file.zip>");return;}var r=p.manager().activate(p.packsDirectory().resolve(a[1]),p.packsDirectory(),p.config());say(i,r.success()?"Active pack changed to "+r.pack().file().getFileName()+".":"Pack was NOT changed: "+r.message());}
 case "info"->{ActivePack x=p.manager().active();say(i,x==null?"No active pack.":x.file().getFileName()+" | size="+x.size()+" | SHA-1="+x.sha1Hex()+" | UUID="+x.id()+" | HTTP="+p.host().running());}
 case "reload"->say(i,p.reload());case "validate"->say(i,p.manager().validateActive(p.config()).message());default->say(i,"Unknown subcommand. Usage: /irp <list|use <file>|info|reload|validate>");}}
 public List<String> suggest(Invocation i){if(!i.source().hasPermission(P))return List.of();String[]a=i.arguments();if(a.length<=1)return part(List.of("list","use","info","reload","validate"),a.length==0?"":a[0]);if(a.length==2&&a[0].equalsIgnoreCase("use"))return part(p.manager().listValid(p.packsDirectory(),p.config()).stream().map(x->x.getFileName().toString()).toList(),a[1]);return List.of();}
 private static List<String>part(List<String>x,String in){String q=in.toLowerCase(java.util.Locale.ROOT);return x.stream().filter(v->v.toLowerCase(java.util.Locale.ROOT).startsWith(q)).sorted().toList();}private static void say(Invocation i,String s){i.source().sendMessage(Component.text("[IRP] "+s));}
}